### ISSUE TITLE
Feature "tokio" does not compile with rustc 1.77.1

### ISSUE THREAD

**Issue by pawurb** [zkat/cacache-rs#69]
Hi. Trying to build project with  rustc 1.77.1 and `tokio` feature enabled outputs multiple compile errors. 

```
  --> /Users/pablo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-io-0.3.30/src/lib.rs:60:12

error[E0308]: mismatched types
  --> /Users/pablo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-13.0.0/src/get.rs:46:9
   |
45 |     ) -> Poll<tokio::io::Result<()>> {
   |          --------------------------- expected `Poll<std::result::Result<(), std::io::Error>>` because of return type
46 |         Pin::new(&mut self.reader).poll_read(cx, buf)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Poll<Result<(), Error>>`, found `Poll<Result<usize, Error>>`
   |
   = note: expected enum `Poll<std::result::Result<(), _>>`
              found enum `Poll<std::result::Result<usize, _>>`

error[E0599]: no method named `poll_shutdown` found for struct `Pin<&mut AsyncWriter>` in the current scope
   --> /Users/pablo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cacache-13.0.0/src/put.rs:170:36
    |
170 |         Pin::new(&mut self.writer).poll_shutdown(cx)
    |                                    ^^^^^^^^^^^^^ method not found in `Pin<&mut AsyncWriter>`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `poll_shutdown`, perhaps you need to implement it:
            candidate #1: `tokio::io::AsyncWrite`
```

As a result I cannot use versions `0.13.0` with my project, it still works with `0.12.0`. Could you look into resolving it?

**Comment by zkat** [comment]
...did tokio seriously do a breaking change on their reader signatures in a non-semver-major release? _seriously_?

**Comment by zkat** [comment]
Anyway this should be a straightforward fix, although I'd like to know what the tokio version shenanigans are. Happy to take and discuss a PR for this.

**Comment by pawurb** [comment]
I think it's tokio `1.37.0`
